services:
  # A Docker web service
  - type: web
    name: "ocr_docker"
    rootDir: ocr_backend
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    env: docker
    envVars:
      - fromGroup: ocr_docker
