services:
  # A Docker web service
  backend:
    - type: web
      name: "ocr_docker"
      build: ./ocr_backend
      context: ./ocr_backend
      env: docker
      rootDir: ocr_backend
      env_file: /etc/secrets/.env
